apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: agents
  labels:
    app: api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: kingbrady/custom-agents-api:0.3.1
        ports:
          - containerPort: 80
        env:
          - name: OLLAMA_API_URL
            value: "http://ollama.llm.svc.cluster.local:11434/api/{path}"
          - name: CORS_ALLOW_ORIGINS
            value: "https://chat.agent.kak.im"
          - name: CORS_ALLOW_CREDENTIALS
            value: "true"
          - name: CORS_ALLOW_METHODS
            value: "GET"
          - name: CORS_ALLOW_HEADERS
            value: "*"
