apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  namespace: agents
  labels:
    app: chat
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chat
        image: kingbrady/custom-agents-chat:0.1.1
        ports:
          - containerPort: 80
